name: Deploy documentation website

inputs:
  debug:
    description: Sets "NODE_ENV" to "debug".
    required: false
    default: false

runs:
  using: composite

  steps:
    - uses: thaibault/install-npm-package-dependencies-action@main
      with:
        debug: ${{ inputs.debug }}

    - name: Trigger deployment script.
      run: yarn run documentation-website
      shell: bash
